fix: Update deployment workflow to ensure proper test execution and improve error handling

diff --git a/.github/workflows/test_deploy_faceubb.yml b/.github/workflows/test_deploy_faceubb.yml
--- a/.github/workflows/test_deploy_faceubb.yml
+++ b/.github/workflows/test_deploy_faceubb.yml
@@ -26,10 +26,10 @@ jobs:
           cd backend || { echo "No se pudo acceder al directorio del backend"; exit 1; }
           npm install
 
-      # - name: Ejecutar pruebas # Ejecuta las pruebas del proyecto
-      #   run: |
-      #     cd backend || { echo "No se pudo acceder al directorio del backend"; exit 1; }
-      #     npm test
+      - name: Ejecutar pruebas # Ejecuta las pruebas del proyecto
+        run: |
+          cd backend || { echo "No se pudo acceder al directorio del backend"; exit 1; }
+          npm test
         env:
           MONGO_URI: ${{ secrets.MONGO_URI }}
 
@@ -40,7 +40,7 @@ jobs:
   # https://docs.github.com/es/actions/security-guides/encrypted-secrets
 
   deploy: # Job para desplegar el proyecto
-    # needs: tests
+    needs: tests
     runs-on: ubuntu-latest
     steps:
       - name: Instalar dependencias (OpenVPN, SSH y sshpass)
@@ -95,10 +95,11 @@ jobs:
 
               # actualizar el código fuente, instalar dependencias y reiniciar servicios
               echo "Actualizando el código fuente..."
-              git fetch origin main
-              git checkout main
-              git reset --hard origin/main
-              git branch --show-current
+              git fetch origin main || { echo "Error al obtener cambios del repositorio"; exit 1; }
+              git checkout main || { echo "Error al cambiar a la rama main"; exit 1; }
+              git reset --hard origin/main || { echo "Error al actualizar el código"; exit 1; }
+              echo "Rama actual: $(git branch --show-current)"
+              echo "Último commit: $(git log -1 --oneline)"
 
               # instalar dependencias del BACKEND
               echo "Instalando dependencias del backend..."
@@ -114,13 +115,13 @@ jobs:
               npm run build 
               cd 
               echo "=== Removiendo datos anteriores de build... ==="
-              rm -rf /var/www/html/gps/*
+              rm -rf /var/www/html/miespacioubb/*
               echo "=== Copiando nuevos archivos al servidor web... ==="
-              cp -r Proyecto-GPS/frontend/dist/* /var/www/html/gps/
+              cp -r MiEspacioUBB/frontend/dist/* /var/www/html/miespacioubb/
               # Cambiar propietario
               echo "=== Cambiando permisos de los archivos... ==="
-              chown -R www-data:www-data /var/www/html/gps
-              chmod -R 755 /var/www/html/gps
+              chown -R www-data:www-data /var/www/html/miespacioubb
+              chmod -R 755 /var/www/html/miespacioubb
               echo "=== Reiniciando Apache... ==="
               apachectl -k graceful
 
